-- Autogenerated: 2025/12/30 01:11:54
local function MakeDatabaseDefaults()

-- profile
local db = Grid2.db.profile
local s, i, m = db.statuses, db.indicators, db.statusMap

db.__template = 'Empty'

i["background"] = { type="background" }

i["tooltip"] = { type="tooltip", showDefault=true }

i["alpha"] = { type="alpha" }
m["alpha"] = { range=99 }

i["border"] = { type="border", color1={a=0,r=0,g=0,b=0} }
m["border"] = { target=50 }

i["health-bar"] = {  type="multibar", location={x=0,y=0,relPoint="CENTER",point="CENTER"}, level=3, textureColor={a=1} }
m["health-bar"] = { ["health-current"]=1 }
i["health-bar-color"] = { type="multibar-color" }
m["health-bar-color"] = { classcolor=50 }

i["text-down"] = { type="text", location={y=4,relPoint="BOTTOM",point="BOTTOM",x=0}, level=6, textlength=6, fontSize=10 }
m["text-down"] = { name=99 }
i["text-down-color"] = { type="text-color" }
m["text-down-color"] = { classcolor=99 }

Grid2:DbUpdateStatusesDefaults()

end

Grid2:DbRegisterProfile( {
name = 'Empty',
desc = 'Minimalistic profile. For advanced users that want to setup a custom profile from scratch.',
func = MakeDatabaseDefaults,
}, 0)
