-- Autogenerated: 2025/12/30 01:11:54
local function MakeDatabaseDefaults()

-- Grid2Frame
local pf = Grid2.db:GetNamespace("Grid2Frame").profile
pf.iconSize = 18
pf.frameHeight = 62
pf.frameWidth = 62
pf.displayZoomedIcons = true

-- profile
local db = Grid2.db.profile
local s, i, m = db.statuses, db.indicators, db.statusMap

db.__template = 'Classic'

s["heals-incoming"] = { includePlayerHeals=true }
s["buffs-Relevant"] = { type="mbuffs", aura_filter={filter="HELPFUL|RAID",sortRule=3}, color1={a=1,r=0,g=1,b=0} }
s["debuffs-Relevant"] = { type="mdebuffs", aura_filter={sortRule=3,filter="HARMFUL|RAID"}, color1={a=1,r=1,g=0,b=0} }

i["icons-debuffs"] = { fontSize=9, borderOpacity=1, disableCooldown=true, fontJustifyV="TOP", borderSize=1, iconSize=24, level=8, tooltipAnchor="ANCHOR_BOTTOMRIGHT", type="icons", enableCooldownText=true, reverseCooldown=true, color1={a=1,b=1,g=1,r=1}, tooltipEnabled=true, ctFontSize=10, disableOmniCC=true, location={y=-2,relPoint="CENTER",point="CENTER",x=0}, fontJustifyH="RIGHT", useStatusColor=true, smartCenter=true }
m["icons-debuffs"] = { ["debuffs-Relevant"]=100 }

i["text-down"] = { type="text", location={y=4,relPoint="BOTTOM",point="BOTTOM",x=0}, level=6, textlength=6, fontSize=10 }
m["text-down"] = { name=99 }
i["text-down-color"] = { type="text-color" }
m["text-down-color"] = { classcolor=99 }

i["icon-left"] = { type="icon", location={y=0,relPoint="LEFT",point="LEFT",x=-2}, level=8, fontSize=8, size=12 }
m["icon-left"] = { ["raid-icon-player"]=155 }

i["icon-center"] = { type="icon", location={y=0,relPoint="CENTER",point="CENTER",x=0}, level=9, fontSize=8, size=20 }

i["icon-right"] = { type="icon", location={y=0,relPoint="RIGHT",point="RIGHT",x=2}, level=8, fontSize=8, size=12 }
m["icon-right"] = { ["dungeon-role"]=150 }

i["health-bar"] = { [1]={horTile="REPEAT",reverse=true,color={a=0.7,r=1,g=0,b=0.737},verTile="REPEAT",texture="Grid2 Shield"}, [2]={color={a=0.5}}, [3]={horTile="REPEAT",color={a=0.7},verTile="REPEAT",prevBar=1,texture="Grid2 Shield"}, [4]={color={a=1,r=0.965,g=0.992,b=1},glowLine=6,prevBar=-1,texture="Grid2 GlowH"}, location={y=0,relPoint="CENTER",point="CENTER",x=0}, level=3, textureColor={a=1}, type="multibar" }
m["health-bar"] = { ["heal-absorbs"]=2, shields=4, ["shields-overflow"]=5, ["heals-incoming"]=3, ["health-current"]=1 }
i["health-bar-color"] = { type="multibar-color" }
m["health-bar-color"] = { classcolor=50 }

i["tooltip"] = { displayUnitOOC=true, type="tooltip" }
m["tooltip"] = { name=50 }

i["alpha"] = { type="alpha" }
m["alpha"] = { range=99 }

i["border"] = { type="border", color1={a=0,r=0,g=0,b=0} }
m["border"] = { target=50 }

i["corner-bottom"] = { type="square", location={y=5,relPoint="BOTTOM",point="BOTTOM",x=0}, level=9, size=7, color1={a=1,r=1,g=1,b=1} }
m["corner-bottom"] = { threat=99 }

i["icons-buffs"] = { tooltipAnchor="ANCHOR_TOPRIGHT", disableOmniCC=true, enableCooldownText=true, tooltipEnabled=true, reverseCooldown=true, color1={a=1,b=0,g=0,r=0}, fontJustifyV="TOP", fontSize=9, borderSize=1, ctFontSize=10, borderOpacity=1, location={y=0,relPoint="TOPLEFT",point="TOPLEFT",x=0}, level=8, type="icons", fontJustifyH="RIGHT" }
m["icons-buffs"] = { ["buffs-Relevant"]=100 }

i["text-up"] = { type="text", percent=true, location={y=-8,relPoint="TOP",point="TOP",x=0}, level=7, textlength=6, fontSize=9 }
m["text-up"] = { charmed=70, ["feign-death"]=96, death=97, vehicle=93, ["health-current"]=65, offline=95 }
i["text-up-color"] = { type="text-color" }
m["text-up-color"] = { charmed=93, ["feign-death"]=96, death=98, classcolor=65, offline=97, vehicle=95 }

i["power-bar"] = { type="bar", backColor={a=1,b=0,g=0,r=0}, color1={a=1,r=0,g=0,b=0}, hideWhenInactive=true, orientation="HORIZONTAL", height=4, backTexture="Grid2 Flat", level=5, location={y=-1,relPoint="BOTTOM",point="BOTTOM",x=0}, texture="Gradient" }
m["power-bar"] = { power=50 }
i["power-bar-color"] = { type="bar-color" }
m["power-bar-color"] = { power=51 }

i["background"] = { type="background" }

Grid2:DbUpdateStatusesDefaults()

end

Grid2:DbRegisterProfile( {
name = 'Classic',
desc = 'Classic Grid2 Unit Frames with vertical health bars and a compact design.',
image = 'Interface\\Addons\\Grid2\\media\\profile-classic',
imageWidth = 352,
imageHeight = 87,
func = MakeDatabaseDefaults,
}, 0)
