--Standardize the way buff and debuff Aura statuses get instantiated from info.
--I want to split the current <object>.name into <object>.<Object Type>Key (so indicatorKey, statusKey etc.) and <object>.name or maybe displayName which would be the possibly localized display name / renamed name / custom name someone typed in.
--Fix health bar ordering / layering
--Defaults system
--Grid2StatusGroupAura
--Fix the color settings for 3 stacks etc.
--Countdown
--Create auras and debuffs
--buffs-raid
--directly use location for indicators instead of grafting it on like right now

--location
	--relative
--status
	--create
	--delete
	--rename
--indicator
	--create
		--specify location up front
	--delete
	--rename
