-- Autogenerated: 2025/12/31 01:51:58
local function MakeDatabaseDefaults()

-- Grid2Frame
local pf = Grid2.db:GetNamespace("Grid2Frame").profile
pf.iconSize = 18
pf.frameWidth = 66
pf.frameHeight = 46
pf.frameBorder = 1
pf.frameBorderDistance = 0
pf.displayZoomedIcons = true
pf.orientation = "HORIZONTAL"
pf.frameBorderColor = { r=0, g=0, b=0, a=1 }

-- Grid2Layout
local pf = Grid2.db:GetNamespace("Grid2Layout").profile
pf.BackgroundTexture = "None"
pf.BorderTexture = "None"
pf.horizontal = false
pf.Padding = 2

-- profile
local db = Grid2.db.profile
local s, i, m = db.statuses, db.indicators, db.statusMap

db.__template = 'Modern'

s["leader"] = { hideInCombat=true }
s["dungeon-role"] = { hideInCombat=true }
s["master-looter"] = { hideInCombat=true }
s["heals-incoming"] = { includePlayerHeals=true }
s["buffs-Relevant"] = { type="mbuffs", color1={a=1,b=0,g=1,r=0}, aura_filter={sortRule=3,filter="HELPFUL|RAID"} }
s["debuffs-Relevant"] = { type="mdebuffs", colors={}, aura_filter={sortRule=3} }

i["text-center"] = { type="text", fontSize=10, location={y=0,relPoint="CENTER",point="CENTER",x=0}, level=7, textlength=6, percent=true }
m["text-center"] = { ["feign-death"]=96, offline=97, name=70, death=98 }
i["text-center-color"] = { type="text-color" }
m["text-center-color"] = { offline=97, ["feign-death"]=96, death=98 }

i["icon-left"] = { type="icon", location={y=0,relPoint="LEFT",point="LEFT",x=-2}, level=8, fontSize=8, size=12 }
m["icon-left"] = { leader=155, ["raid-icon-player"]=156 }

i["border"] = { color1={a=0,b=0,g=0,r=0}, type="border" }
m["border"] = { target=50, ["debuffs-DispellableByMe"]=51 }

i["icon-center"] = { type="icon", location={y=0,relPoint="CENTER",point="CENTER",x=0}, level=9, fontSize=8, size=20 }
m["icon-center"] = { phased=50, resurrection=54, death=53, ["ready-check"]=55, offline=52, summon=51 }

i["icon-right"] = { type="icon", location={y=0,relPoint="RIGHT",point="RIGHT",x=2}, level=8, fontSize=8, size=12 }
m["icon-right"] = { ["dungeon-role"]=150, ["raid-icon-target"]=151 }

i["health-bar"] = { [1]={horTile="REPEAT",reverse=true,color={a=0.7,b=0.737,g=0,r=1},texture="Grid2 Shield",verTile="REPEAT"}, [2]={color={a=0.7}}, [3]={horTile="REPEAT",color={a=0.7},texture="Grid2 Shield",prevBar=1,verTile="REPEAT"}, [4]={color={a=1,b=1,g=0.992,r=0.965},prevBar=-1,glowLine=6,texture="Grid2 GlowV"}, location={y=0,relPoint="CENTER",point="CENTER",x=0}, type="multibar", level=3, textureColor={a=1} }
m["health-bar"] = { ["heal-absorbs"]=2, shields=4, ["heals-incoming"]=3, ["health-current"]=1, ["shields-overflow"]=5 }
i["health-bar-color"] = { type="multibar-color" }
m["health-bar-color"] = { classcolor=50 }

i["alpha"] = { type="alpha" }
m["alpha"] = { range=99 }

i["buffs-icons"] = { tooltipAnchor="ANCHOR_TOPRIGHT", fontSize=9, borderOpacity=1, tooltipEnabled=true, fontJustifyH="RIGHT", disableCooldown=true, disableOmniCC=true, fontJustifyV="TOP", enableCooldownText=true, borderSize=1, ctFontSize=10, reverseCooldown=true, location={y=0,relPoint="TOPLEFT",point="TOPLEFT",x=0}, level=8, color1={a=1,r=0,g=0,b=0}, type="icons" }
m["buffs-icons"] = { ["buffs-Relevant"]=100 }

i["corner-bottom"] = { type="square", color1={a=0.616,b=0,g=0,r=0}, location={y=4,relPoint="BOTTOM",point="BOTTOM",x=0}, level=9, borderSize=1, size=8 }
m["corner-bottom"] = { threat=99 }

i["power-bar"] = { type="bar", backColor={a=1,r=0,g=0,b=0}, color1={a=1,b=0,g=0,r=0}, hideWhenInactive=true, backTexture="Grid2 Flat", location={y=0,relPoint="BOTTOM",point="BOTTOM",x=0}, height=3, level=5, orientation="HORIZONTAL", texture="Gradient" }
m["power-bar"] = { power=50 }
i["power-bar-color"] = { type="bar-color" }
m["power-bar-color"] = { power=51 }

i["debuffs-icons"] = { fontSize=9, borderOpacity=1, disableCooldown=true, fontJustifyV="TOP", borderSize=1, iconSize=22, level=8, tooltipAnchor="ANCHOR_BOTTOMRIGHT", type="icons", enableCooldownText=true, reverseCooldown=true, color1={a=1,r=1,g=1,b=1}, ctFontSize=10, location={y=0,relPoint="BOTTOMLEFT",point="BOTTOMLEFT",x=0}, useStatusColor=true, fontJustifyH="RIGHT", disableOmniCC=true, tooltipEnabled=true }
m["debuffs-icons"] = { ["debuffs-Relevant"]=50 }

i["private-auras"] = { maxIcons=1, type="privateauras", location={y=0,relPoint="BOTTOMRIGHT",point="BOTTOMRIGHT",x=0}, level=9, load={unitType={self=true,player=true}}, iconSize=22 }

i["tooltip"] = { showDefault=true, type="tooltip" }

i["background"] = { type="background" }

Grid2:DbUpdateStatusesDefaults()

end

Grid2:DbRegisterProfile( {
name = 'Modern',
desc = 'Modern unit frames with horizontal health bars and a compact design.',
image = [[Interface\Addons\Grid2Options\media\profile-modern]],
imageWidth = 257,
imageHeight = 60,
func = MakeDatabaseDefaults,
} )
