-- Autogenerated: 2026/01/01 17:01:10
local function MakeDatabaseDefaults()

-- Grid2Frame
local pf = Grid2.db:GetNamespace("Grid2Frame").profile
pf.frameBorder = 1
pf.iconSize = 18
pf.frameBorderDistance = 0
pf.frameHeight = 46
pf.displayZoomedIcons = true
pf.orientation = "HORIZONTAL"
pf.frameBorderColor = { r=0, g=0, b=0, a=1 }
pf.frameWidth = 92

-- Grid2Layout
local pf = Grid2.db:GetNamespace("Grid2Layout").profile
pf.BackgroundTexture = "None"
pf.BorderTexture = "None"
pf.Padding = 2
pf.horizontal = false

-- profile
local db = Grid2.db.profile
local s, i, m = db.statuses, db.indicators, db.statusMap

db.__template = 'Blizzard'

s["threat"] = { color3= {g=.5} }
s["leader"] = { hideInCombat=true }
s["dungeon-role"] = { hideInCombat=true }
s["master-looter"] = { hideInCombat=true }
s["heals-incoming"] = { includePlayerHeals=true }
s["debuffs-Relevant"] = { type="mdebuffs", color1={a=1,b=0,g=0,r=1}, aura_filter={sortRule=3} }
s["buffs-Relevant"] = { type="mbuffs", color1={a=1,b=0,g=1,r=0}, aura_filter={sortRule=3,filter="HELPFUL|RAID"} }

i["icon-left"] = { type="icon", disableCooldown=true, location={y=0,relPoint="LEFT",point="LEFT",x=-2}, level=8, fontSize=8, size=12 }
m["icon-left"] = { ["raid-icon-player"]=156 }

i["border"] = { color1={a=0,b=0,g=0,r=0}, type="border" }
m["border"] = { target=50, ["debuffs-DispellableByMe"]=51 }

i["background"] = { type="background" }

i["icon-center"] = { disableStack=true, type="icon", fontSize=8, location={y=0,relPoint="CENTER",point="CENTER",x=0}, level=9, disableCooldown=true, size=20 }
m["icon-center"] = { phased=50, resurrection=54, death=53, ["ready-check"]=55, offline=52, summon=51 }

i["private-auras"] = { maxIcons=1, type="privateauras", location={y=14,relPoint="CENTER",point="CENTER",x=0}, level=9, load={unitType={self=true,player=true}}, iconSize=24 }

i["icon-right"] = { type="icon", disableCooldown=true, location={y=0,relPoint="RIGHT",point="RIGHT",x=2}, level=8, fontSize=8, size=12 }
m["icon-right"] = { ["raid-icon-target"]=151 }

i["health-bar"] = { [1]={horTile="REPEAT",reverse=true,color={a=0.7,b=0.737,g=0,r=1},texture="Grid2 Shield",verTile="REPEAT"}, [2]={color={a=0.7}}, [3]={horTile="REPEAT",color={a=0.7},texture="Grid2 Shield",prevBar=1,verTile="REPEAT"}, [4]={color={a=1,b=1,g=0.992,r=0.965},prevBar=-1,glowLine=6,texture="Grid2 GlowV"}, location={y=0,relPoint="CENTER",point="CENTER",x=0}, type="multibar", level=3, textureColor={a=1} }
m["health-bar"] = { ["heal-absorbs"]=2, shields=4, ["health-current"]=1, ["heals-incoming"]=3, ["shields-overflow"]=5 }
i["health-bar-color"] = { type="multibar-color" }
m["health-bar-color"] = { classcolor=50 }

i["tooltip"] = { showDefault=true, type="tooltip" }

i["alpha"] = { type="alpha" }
m["alpha"] = { range=99 }

i["buffs-icons"] = { tooltipAnchor="ANCHOR_RIGHT", fontSize=9, enableCooldownText=true, tooltipEnabled=true, reverseCooldown=true, disableOmniCC=true, color1={a=1,r=0,g=0,b=0}, borderOpacity=1, borderSize=1, ctFontSize=10, fontJustifyH="RIGHT", location={y=4,relPoint="BOTTOMRIGHT",point="BOTTOMRIGHT",x=-1}, level=8, fontJustifyV="TOP", type="icons" }
m["buffs-icons"] = { ["buffs-Relevant"]=100 }

i["role-icons"] = { disableStack=true, type="icons", disableCooldown=true, level=9, iconSize=12, location={y=0,relPoint="TOPRIGHT",point="TOPRIGHT",x=-1} }
m["role-icons"] = { ["dungeon-role"]=52, leader=50, ["master-looter"]=51 }

i["power-bar"] = { type="bar", backColor={a=1,r=0,g=0,b=0}, color1={a=1,b=0,g=0,r=0}, hideWhenInactive=true, location={y=0,relPoint="BOTTOM",point="BOTTOM",x=0}, backTexture="Grid2 Flat", orientation="HORIZONTAL", level=5, height=3, texture="Gradient" }
m["power-bar"] = { power=50 }
i["power-bar-color"] = { type="bar-color" }
m["power-bar-color"] = { power=51 }

i["text-name"] = { type="text", fontSize=10, location={y=-2,relPoint="TOPLEFT",point="TOPLEFT",x=2}, level=7, percent=true, textlength=8 }
m["text-name"] = { ["feign-death"]=96, offline=97, name=70, death=98 }
i["text-name-color"] = { type="text-color" }
m["text-name-color"] = { offline=97, ["feign-death"]=96, death=98 }

i["debuffs-icons"] = { fontSize=9, borderOpacity=1, disableCooldown=true, fontJustifyV="TOP", borderSize=1, iconSize=26, level=8, tooltipAnchor="ANCHOR_LEFT", type="icons", enableCooldownText=true, reverseCooldown=true, color1={a=1,r=1,g=1,b=1}, fontJustifyH="RIGHT", ctFontSize=12, useStatusColor=true, location={y=4,relPoint="BOTTOMLEFT",point="BOTTOMLEFT",x=1}, disableOmniCC=true, tooltipEnabled=true, fontOffsetY=4 }
m["debuffs-icons"] = { ["debuffs-Relevant"]=50 }

Grid2:DbUpdateStatusesDefaults()

end

Grid2:DbRegisterProfile( {
name = 'Blizzard',
desc = 'Blizzard style unit frames.',
image = [[Interface\Addons\Grid2Options\media\profile-blizzard]],
imageWidth = 355,
imageHeight = 62,
func = MakeDatabaseDefaults,
} )
