-- Autogenerated: 2025/12/31 16:47:36
local function MakeDatabaseDefaults()

-- Grid2Frame
local pf = Grid2.db:GetNamespace("Grid2Frame").profile
pf.frameBorder = 1
pf.iconSize = 18
pf.frameBorderDistance = 0
pf.frameWidth = 92
pf.frameHeight = 46
pf.displayZoomedIcons = true
pf.orientation = "HORIZONTAL"
pf.frameBorderColor = { r=0, g=0, b=0, a=1 }

-- Grid2Layout
local pf = Grid2.db:GetNamespace("Grid2Layout").profile
pf.BackgroundTexture = "None"
pf.BorderTexture = "None"
pf.Padding = 2
pf.horizontal = false

-- profile
local db = Grid2.db.profile
local s, i, m = db.statuses, db.indicators, db.statusMap

db.__template = 'Blizzard'

s["buffs-Relevant"] = { type="mbuffs", aura_filter={filter="HELPFUL|RAID",sortRule=3}, color1={a=1,r=0,g=1,b=0} }
s["master-looter"] = { hideInCombat=true }
s["dungeon-role"] = { hideInCombat=true }
s["heals-incoming"] = { includePlayerHeals=true }
s["leader"] = { hideInCombat=true }
s["debuffs-Relevant"] = { type="mdebuffs", aura_filter={sortRule=3,filter="HARMFUL|RAID"}, color1={a=1,r=1,g=0,b=0} }

i["icon-left"] = { type="icon", location={y=0,relPoint="LEFT",point="LEFT",x=-2}, disableCooldown=true, level=8, fontSize=8, size=12 }
m["icon-left"] = { ["raid-icon-player"]=156 }

i["background"] = { type="background" }

i["icon-center"] = { disableStack=true, type="icon", fontSize=8, location={y=0,relPoint="CENTER",point="CENTER",x=0}, level=9, disableCooldown=true, size=20 }
m["icon-center"] = { phased=50, resurrection=54, death=53, ["ready-check"]=55, offline=52, summon=51 }

i["private-auras"] = { maxIcons=1, type="privateauras", location={y=14,relPoint="CENTER",point="CENTER",x=0}, level=9, load={unitType={self=true,player=true}}, iconSize=24 }

i["icon-right"] = { type="icon", location={y=0,relPoint="RIGHT",point="RIGHT",x=2}, disableCooldown=true, level=8, fontSize=8, size=12 }
m["icon-right"] = { ["raid-icon-target"]=151 }

i["health-bar"] = { [1]={horTile="REPEAT",reverse=true,color={a=0.7,r=1,g=0,b=0.737},verTile="REPEAT",texture="Grid2 Shield"}, [2]={color={a=0.7}}, [3]={horTile="REPEAT",color={a=0.7},verTile="REPEAT",prevBar=1,texture="Grid2 Shield"}, [4]={color={a=1,r=0.965,g=0.992,b=1},glowLine=6,prevBar=-1,texture="Grid2 GlowH"}, location={y=0,relPoint="CENTER",point="CENTER",x=0}, textureColor={a=1}, level=3, type="multibar" }
m["health-bar"] = { ["heal-absorbs"]=2, shields=4, ["shields-overflow"]=5, ["heals-incoming"]=3, ["health-current"]=1 }
i["health-bar-color"] = { type="multibar-color" }
m["health-bar-color"] = { classcolor=50 }

i["tooltip"] = { showDefault=true, type="tooltip" }

i["alpha"] = { type="alpha" }
m["alpha"] = { range=99 }

i["buffs-icons"] = { tooltipAnchor="ANCHOR_RIGHT", disableOmniCC=true, borderOpacity=1, tooltipEnabled=true, fontJustifyH="RIGHT", fontSize=9, color1={a=1,b=0,g=0,r=0}, enableCooldownText=true, borderSize=1, ctFontSize=10, reverseCooldown=true, location={y=4,relPoint="BOTTOMRIGHT",point="BOTTOMRIGHT",x=-1}, level=8, type="icons", fontJustifyV="TOP" }
m["buffs-icons"] = { ["buffs-Relevant"]=100 }

i["debuffs-icons"] = { fontSize=9, borderOpacity=1, disableCooldown=true, fontJustifyV="TOP", borderSize=1, iconSize=26, level=8, tooltipAnchor="ANCHOR_LEFT", type="icons", enableCooldownText=true, reverseCooldown=true, fontOffsetY=4, color1={a=1,b=1,g=1,r=1}, ctFontSize=12, tooltipEnabled=true, location={y=3,relPoint="BOTTOMLEFT",point="BOTTOMLEFT",x=1}, disableOmniCC=true, fontJustifyH="RIGHT", useStatusColor=true }
m["debuffs-icons"] = { ["debuffs-Relevant"]=50 }

i["border"] = { type="border", color1={a=0,r=0,g=0,b=0} }
m["border"] = { target=50, threat=51 }

i["power-bar"] = { type="bar", backColor={a=1,b=0,g=0,r=0}, color1={a=1,r=0,g=0,b=0}, hideWhenInactive=true, orientation="HORIZONTAL", height=3, backTexture="Grid2 Flat", level=5, location={y=0,relPoint="BOTTOM",point="BOTTOM",x=0}, texture="Gradient" }
m["power-bar"] = { power=50 }
i["power-bar-color"] = { type="bar-color" }
m["power-bar-color"] = { power=51 }

i["text-name"] = { type="text", percent=true, location={y=-2,relPoint="TOPLEFT",point="TOPLEFT",x=2}, level=7, textlength=8, fontSize=10 }
m["text-name"] = { name=70, offline=97, ["feign-death"]=96, death=98 }
i["text-name-color"] = { type="text-color" }
m["text-name-color"] = { offline=97, ["feign-death"]=96, death=98 }

i["role-icons"] = { disableStack=true, type="icons", disableCooldown=true, level=9, location={y=0,relPoint="TOPRIGHT",point="TOPRIGHT",x=-1}, iconSize=12 }
m["role-icons"] = { ["dungeon-role"]=52, leader=50, ["master-looter"]=51 }

Grid2:DbUpdateStatusesDefaults()

end

Grid2:DbRegisterProfile( {
name = 'Blizzard',
desc = 'Blizzard style unit frames.',
image = [[Interface\Addons\Grid2Options\media\profile-blizzard]],
imageWidth = 355,
imageHeight = 62,
func = MakeDatabaseDefaults,
} )
